### ISSUE TITLE
Coordinate doesn't match problems for tracer

### ISSUE THREAD

**Issue by peijin94** [predsci/PsiPy#77]
The script 'examples/tracing/plot_tracing_mpl.py' didn't run successfully for corona MAS model download from MHDweb
The tracer fails with error: dimension doesn't match, I printed out the variables, looks like this:

```python

Variable
--------
Name: bt
Grid size: (299, 143, 254) (phi, theta, r)
Timesteps: 1


Variable
--------
Name: bp
Grid size: (300, 142, 254) (phi, theta, r)
Timesteps: 1


Variable
--------
Name: br
Grid size: (657, 321, 256) (phi, theta, r)
Timesteps: 2
```

Is this output normal?
Do we need to do more interpolations and alignments for the data before B-field tracing?

**Comment by thepeteriley** [comment]
This shouldn't be an issue. What was the specific run that you're trying to trace field lines for? It appears that there are two Br files in the directory, with one having more than double the resolution. This shouldn't be the case. All field line component files should have ~300x143x255 resolution (+/- 1 because of the staggered mesh. It's possible that the reader is picking up a rogue file in the directory.

**Comment by peijin94** [comment]
It is "hmi__high-cor-thermo2-exp01__high-hel-poly-exp01" for 2022-05-19 the corona model.
Indeed, there are two files for B_r: br002.hdf and br_r0.hdf.
Looks like it will load br_r0.hdf automatically for model['br'].

It works when I move 'br_r0.hdf' out of the data folder. 🙌

Thanks.

**Comment by thepeteriley** [comment]
Great, thanks for checking that. But you've raised a good point...this is a bug :) br_r0 is the 2D boundary file for that run. It should be in the directory as part of the complete run, so we'll need to correct the reading behaviour to account for it.
